// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKXkJYA9HgSPzqhv0QvD6G5tcBUEfVNio',
    appId: '1:675146107376:web:58fbb84675e6a0b1a7f535',
    messagingSenderId: '675146107376',
    projectId: 'terapiasdaluna-4850b',
    authDomain: 'terapiasdaluna-4850b.firebaseapp.com',
    storageBucket: 'terapiasdaluna-4850b.appspot.com',
    measurementId: 'G-1DG4Y7601L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6UiuItEtnILzn6k32dNmDy6s6xruw5NE',
    appId: '1:675146107376:android:67ec772b467ac80ea7f535',
    messagingSenderId: '675146107376',
    projectId: 'terapiasdaluna-4850b',
    storageBucket: 'terapiasdaluna-4850b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzy2PHAWZJJaf-HLM-A5F1i_XfH8j9lKQ',
    appId: '1:675146107376:ios:057bad00c5589d6ba7f535',
    messagingSenderId: '675146107376',
    projectId: 'terapiasdaluna-4850b',
    storageBucket: 'terapiasdaluna-4850b.appspot.com',
    iosClientId: '675146107376-vdercr54v5rm9k7mbt2evspe3eesvisg.apps.googleusercontent.com',
    iosBundleId: 'com.terapiasdalunaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzy2PHAWZJJaf-HLM-A5F1i_XfH8j9lKQ',
    appId: '1:675146107376:ios:057bad00c5589d6ba7f535',
    messagingSenderId: '675146107376',
    projectId: 'terapiasdaluna-4850b',
    storageBucket: 'terapiasdaluna-4850b.appspot.com',
    iosClientId: '675146107376-vdercr54v5rm9k7mbt2evspe3eesvisg.apps.googleusercontent.com',
    iosBundleId: 'com.example.terapiasdalunaFlutter',
  );
}
